### PR TITLE
Update to v2023-07-28

### PR DESCRIPTION
**Pull request by demorest**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by demorest** [comment]
@conda-forge-admin, please rerender

**Comment by demorest** [comment]
Seem to be various issues with the OSX build.  I've revived my local Mac dev environment and will continue debugging there.

**Comment by demorest** [comment]
So there seems to be an issue with the latest version of the C++ std library now in use by conda-forge for OSX builds (LLVM libc++ v16).  It is not happy with using `std::complex` on user-defined types.  Unfortunately this is done pretty extensively in psrchive (mainly things like `std::complex<Estimate<double>>`).  Here is a report from another project that ran into this: https://github.com/stan-dev/cmdstan/issues/1158

The conda-forge linux builds use gcc/libstd++ and do not have this problem.

I'm not sure there is a simple fix.. @straten any thoughts?

**Comment by straten** [comment]
> ... not happy with using `std::complex` on user-defined types. Unfortunately this is done pretty extensively in psrchive (mainly things like `std::complex<Estimate<double>>`).  ...
> 
> I'm not sure there is a simple fix.. @straten any thoughts?

Hi Paul, we once had the same trouble when using the Intel compiler (icc) and, if I remember correctly, I worked around it by implementing my own complex template class ... however, I don't see any remnants of this code in the repository.  It might have been only an idea.  I'll keep digging.

**Comment by straten** [comment]
In psrchive/config/complex_template.m4, there is a very simple test for a "good" complex<T> template that simply checks that it is possible to compute sqrt(z).  We could try adding to the test to catch the case that is causing compilation to fail, then see if the HAVE_COMPLEX_TEMPLATE macro is properly heeded throughout the code.  I'm not running on a Mac these days, but I can borrow Asha's to see if I can reproduce the problem.

**Comment by straten** [comment]
It looks like HAVE_COMPLEX_TEMPLATE is checked only in More/Polarimetry/Polar_solve.C ... so we may need to
1. ensure that this macro is not defined when compiling with LLVM libc++ v16; and
2. add more checks for HAVE_COMPLEX_TEMPLATE wherever compilation fails.
(sorry about the trouble!)

**Comment by demorest** [comment]
Adding an explicit implementation of complex multiply for Estimate may have worked around it.. will test some more and let you know (before you spend too much time on it).

**Comment by demorest** [comment]
Ok this seems to be successfully building now, yay!

Willem can you please take a look [here](https://github.com/demorest/psrchive-feedstock/blob/v2023-07-28/recipe/0006-complex-estimate.patch) and let me know what you think?  I added implementations of `operator*` and `norm` to the Estimate class to handle these operations on `std::complex<Estimate>`.  Is there anything we could do to test this?  The very basic tests already included in the packaging are passing but I'm not sure they cover this usage.

**Comment by straten** [comment]
This looks good to me, Paul.  Thanks for the fix!

**Comment by demorest** [comment]
I wanted to test the complex changes a bit more before releasing this, tests were done in https://github.com/straten/epsic/pull/4 and seem to be passing.

Then https://sourceforge.net/p/psrchive/bugs/465/ came up again and I realized it's breaking some important (to me) functionality.  That may be wrapping up soon, if so I will likely just close this and package a new release with the fix.

**Comment by demorest** [comment]
Going to skip this version due to issues noted here.  A newer version (2023-10-02; #39 ) is building successfully and will be merged shortly.

**Pull request closed without merging**
